### ISSUE TITLE
Using some opam variables results in error `Undefined boolean filter value`

### ISSUE THREAD

**Issue by gridbugs** [kit-ty-kate/opam-build#4]
This can be reproduced by running `opam build` from the `opam-build` repo itself:
```
git clone https://github.com/kit-ty-kate/opam-build
cd opam-build
opam build
...
∗ installed opam-state.2.1.5
∗ installed opam-client.2.1.5
Done.
# Run eval $(opam env) to update the current shell environment
opam-build: internal error, uncaught exception:
            Failure("Undefined boolean filter value: opam-version >= \"2.2\"")
```

Another example with a different variable:
```
git clone https://github.com/gridbugs/llama
cd llama
git checkout 0.0.1   # otherwise this will fail for a different reason
opam build
...
∗ installed ctypes.0.20.2
∗ installed tsdl.1.0.0
Done.
opam-build: internal error, uncaught exception:
            Failure("Undefined boolean filter value: os = \"linux\"")
```

My OS is NixOS and my opam is version 2.1.5.

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/kit-ty-kate/opam-build/commit/9165af3d6ea26f3ffb6272082811101550a168c0

I thought is was fine to assign the package in a source directory a custom version, but it's not possible at the moment. I've opened an issue for that upstream: https://github.com/ocaml/opam/issues/5855

Thanks for your bug-report!
