### ISSUE TITLE
`opam build` always prints warning "No invariant was set..."

### ISSUE THREAD

**Issue by gridbugs** [kit-ty-kate/opam-build#5]
When running `opam build` in some project, the output includes:
```
Switch invariant: []
[NOTE] No invariant was set, you may want to use `opam switch set-invariant' to keep a stable compiler version on upgrades.
```

This happens regardless of whether a switch invariant is set.

Also of note is that when I run `opam switch create .` the corresponding part of the output says:
```
Switch invariant: ["ocaml" {>= "4.05.0"}]
```
...regardless of what my switch invariant was set to before running the command, and running that command seems to change my switch invariant (to the reported value). I assume that the switch invariant (reported by running `opam switch invariant`) is specific to the current switch and this command is creating a new switch with the reported invariant. 

It might be that `opam build` isn't acting incorrectly wrt switch invariants, however I think the fact that it reports this note is confusing and for consistency my opinion is that it should match the behaviour of `opam switch create .` unless there's a good reason to deviate.

My OS is NixOS and my opam is version 2.1.5.

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/kit-ty-kate/opam-build/commit/ee9699688f4f9c64454d464e7943982d6ff7eaad

The empty invariant is not ideal but I don't think setting it to the opam default invariant is a good alternative. Instead, ideally, I'd like the invariant to be the formula of all the dependencies but that's a bit more work, actually maybe not but I'd like to separate the two issues so I opened https://github.com/kit-ty-kate/opam-build/issues/10

Thanks for your bug-report!
